In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [18]:
import warnings
warnings.filterwarnings('ignore')

## import database

In [19]:
conn = sqlite3.connect('customer_churn.db')

sql_query = """
    select name 
    from sqlite_master 
    where type = 'table'
"""

In [20]:
tables = pd.read_sql(sql_query, conn)
tables

              name
0      db_customer
1  db_subscription
2       db_support

In [21]:
for table_name in tables['name']:
    df = pd.read_sql(f"Select * from {table_name}", conn)
    globals()[f"df_{table_name}"] = df
    print(f'Create dataframe : df_{table_name}')

conn.close()

Create dataframe : df_db_customer
Create dataframe : df_db_subscription
Create dataframe : df_db_support

In [22]:
conn = sqlite3.connect('customer_churn.db')

for table_name in tables['name']:
    print(f"\n Table name: {table_name}")

    col_query = f"pragma table_info({table_name});"
    col = pd.read_sql(col_query, conn)
    print("Columns: ")
    print(col['name'].tolist())

 Table name: db_customer
Columns:
['customerid', 'name', 'country', 'state', 'gender', 'dob', 'interests', 'pincode']

 Table name: db_subscription
Columns:
['customerid', 'subscription_start_date', 'subscription_type', 'renewal_date', 'plan_type', 'contract_type', 'cancellation_date', 'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score']

 Table name: db_support
Columns:
['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1', 'comment']

# Data Cleaning

In [23]:
df_db_customer.head(5)

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

In [ ]:
df_db_customer.info() #type: ignore

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     str
 1   name        21 non-null     str
 2   country     18 non-null     str
 3   state       21 non-null     str
 4   gender      21 non-null     str
 5   dob         21 non-null     str
 6   interests   4 non-null      str
 7   pincode     0 non-null      object
dtypes: object(1), str(7)
memory usage: 1.4+ KB

In [25]:
df_customer = df_db_customer.copy()